# Generated by Django 6.0.5 on 2026-05-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='position',
        ),
        migrations.AddField(
            model_name='productimage',
            name='content_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='size_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.product'),
        ),
    ]
