# Generated by Django 6.0.5 on 2026-05-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="position",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ("position", "id")},
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="products.product"),
        ),
    ]
