# Generated by Django 6.0.5 on 2026-06-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_position_and_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='large',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products/variants/'),
        ),
    ]
