# Generated by Django 6.0.5 on 2026-05-13 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0002_alter_monthlycut_options_monthlycut_cutoff_date_and_more'),
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='closed_by_cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_expenses', to='cuts.monthlycut'),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_closed_by_cut',
            field=models.BooleanField(default=False),
        ),
    ]
