# Generated by Django 6.0.5 on 2026-05-13 05:13

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycut',
            options={'ordering': ('-cutoff_date', '-id')},
        ),
        migrations.AddField(
            model_name='monthlycut',
            name='cutoff_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='monthlycut',
            name='finished_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlycut',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monthlycut',
            name='status',
            field=models.CharField(choices=[('running', 'En ejecucion'), ('completed', 'Completado'), ('failed', 'Fallido')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlycut',
            name='period',
            field=models.CharField(help_text='Formato YYYY-MM', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='monthlycut',
            constraint=models.UniqueConstraint(fields=('period', 'cutoff_date'), name='uniq_cut_period_cutoff_date'),
        ),
    ]
